name: Deploy Google Cloud Workflow

on:
  push:
    branches:
      - main  # Trigger the action when pushing to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Deploy Workflow to Google Cloud
      run: |
        gcloud workflows deploy procrastination-workflow --source=pipelines/gcp-workflow.yml --location=us-central1

    - name: Execute Workflow
      run: |
        gcloud workflows run my-cloud-run-workflow --location=us-central1 --data='{"service_url": "${{ secrets.CLOUD_RUN_URL }}"}'
